- name: Turn Swap off
  raw: sudo swapoff -a

- name: Install k8s APT repo GPG key
  apt_key:
    url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    state: present

- name: Install Docker APT repo GPG key
  apt_key:
    id: F76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    state: present

- name: Setup Docker APT repo
  apt_repository:
    repo: deb http://apt.dockerproject.org/repo ubuntu-xenial main
    state: present

- name: Setup k8s APT repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install docker and kubernetes packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - docker-engine=1.13.1-0~ubuntu-xenial
    - kubelet=1.11.9-00
    - kubeadm=1.11.9-00
    - kubectl=1.11.9-00
    - kubernetes-cni=0.7.5-00

- name: Pip install docker for Ansible's docker_login and docker_service modules
  pip:
    name: "docker"


- name: configure docker to use journald
  copy:
    content: |
      {
        "log-driver": "journald"
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart docker

- name: add hosts
  lineinfile:
    dest: "/etc/hosts"
    regexp: ".*{{ hostvars[item].ansible_hostname }}$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}"
    state: present
  when: hostvars[item].ansible_hostname is defined
  with_items: "{{groups['all'] | default([])}}"

- name: add localhost to system hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 localhost'

- name: copy volumes
  copy:
    src: files/volumes
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: '0777'


- name: Create volume directories
  file:
    path: "/tmp/data{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu 
    mode: '0777'
    recurse: yes
  with_sequence: count=10


